name: wx天气预报推送

on:
  schedule:
    # 启动时间，为 UTC 时间对应北京时间早7点
    - cron : '00 23 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Say hello to your girlfriend every day

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install pip
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run weather
      run: |
        python main.py

    env:
      APP_KEY: ${{ secrets.APP_KEY }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_IDS: ${{ secrets.USER_IDS }}
      START_DATE: ${{ secrets.START_DATE }}
      NAME: ${{ secrets.NAME }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}